export interface Task {
  id: number
  title: string
  description: string | null
  projectId: number | null
  learningTrackId: number | null
  
  // PINCH System
  pinchScore: number
  pinchPassion: number
  pinchInterest: number
  pinchNovelty: number
  pinchChallenge: number
  pinchHurry: number
  pinchLastCalc: Date | null

  // Energy & Scheduling
  energyLevel: 'low' | 'medium' | 'high' | 'peak'
  estimatedMinutes: number
  actualMinutes: number | null
  bestTimeOfDay: string

  // Status & Priority
  priority: 'low' | 'medium' | 'high' | 'urgent'
  status: 'inbox' | 'today' | 'scheduled' | 'in_progress' | 'done' | 'parked' | 'delegated'

  // ADHD-specific
  isMicroTask: boolean
  parentTaskId: number | null
  aiBreakdown: string | null // JSON string of steps
  microSteps: string // JSON string of subtask list
  
  dopamineRewardId: number | null
  urgencyBoost: string | null
  noveltyTwist: string | null
  challengeFrame: string | null

  // Context
  tags: string // JSON string of tags
  attachments: string // JSON string
  contextNotes: string | null

  dueDate: Date | null
  scheduledFor: Date | null
  completedAt: Date | null
  createdAt: Date
  updatedAt: Date | null
}

export interface Project {
  id: number
  name: string
  description: string | null
  emoji: string
  color: string
  status: 'active' | 'paused' | 'completed' | 'graveyard'
  
  graveyardReason: string | null
  graveyardLessons: string | null
  graveyardCompletionPct: number
  graveyardCelebration: string | null
  graveyardedAt: Date | null

  totalFocusMinutes: number
  taskCount: number
  completedTaskCount: number
  xpEarned: number
  targetDate: Date | null
  createdAt: Date
  updatedAt: Date | null
  completedAt: Date | null
}

export interface LearningTrack {
  id: number
  title: string
  emoji: string
  description: string | null
  source: string | null
  sourceUrl: string | null

  totalLessons: number
  completedLessons: number
  currentLesson: number
  currentLessonTitle: string | null
  lastPosition: string | null

  dailyGoalMinutes: number
  whyStarted: string | null
  commitment: string | null
  status: 'active' | 'paused' | 'completed' | 'parked'

  currentStreakDays: number
  longestStreakDays: number
  lastStudiedAt: Date | null

  totalStudyMinutes: number
  xpEarned: number
  pinchScore: number

  createdAt: Date
  completedAt: Date | null
}

export interface LearningLesson {
  id: number
  trackId: number
  order: number
  title: string
  estimatedMinutes: number
  actualMinutes: number | null
  status: 'pending' | 'in_progress' | 'done' | 'skipped'
  notes: string | null
  keyPoints: string | null // JSON string
  completedAt: Date | null
}

export interface LearningPath {
  id: number
  title: string
  emoji: string
  description: string | null
  goal: string | null
  source: string | null
  sourceUrl: string | null
  isAiGenerated: boolean
  aiRoadmap: string | null
  difficulty: 'beginner' | 'intermediate' | 'advanced'
  learningStyle: 'visual' | 'auditory' | 'reading' | 'kinesthetic' | 'mixed'
  totalModules: number
  completedModules: number
  currentModuleId: number | null
  lastPosition: string | null
  dailyGoalMinutes: number
  whyStarted: string | null
  commitment: string | null
  abandonmentRisk: number
  flashcardDeckId: number | null
  status: 'active' | 'paused' | 'completed' | 'parked'
  totalStudyMinutes: number
  currentStreakDays: number
  longestStreakDays: number
  lastStudiedAt: Date | null
  xpEarned: number
  pinchScore: number
  retentionScore: number
  createdAt: Date
  completedAt: Date | null
}

export interface LearningModule {
  id: number
  pathId: number
  order: number
  title: string
  type: 'lesson' | 'quiz' | 'feynman' | 'project' | 'review'
  content: string | null
  estimatedMinutes: number
  microchunkCount: number
  status: 'pending' | 'in_progress' | 'done' | 'skipped'
  autoGeneratedCards: boolean
  cardCount: number
  notes: string | null
  keyPoints: string | null
  completedAt: Date | null
}

export interface FlashcardDeck {
  id: number
  name: string
  emoji: string
  description: string | null
  pathId: number | null
  targetRetention: number
  totalCards: number
  dueToday: number
  newToday: number
  masteredCards: number
  createdAt: Date
}

export interface Flashcard {
  id: number
  deckId: number
  pathId: number | null
  moduleId: number | null
  front: string
  back: string
  hint: string | null
  tags: string
  mediaType: 'text' | 'image' | 'code' | 'math' | 'mixed'
  stability: number
  difficulty: number
  retrievability: number
  dueDate: Date | null
  lastReviewDate: Date | null
  nextInterval: number
  reviewCount: number
  lapseCount: number
  state: 'new' | 'learning' | 'review' | 'relearning' | 'mastered'
  isAiGenerated: boolean
  createdAt: Date
}

export interface FSRSReview {
  id: number
  cardId: number
  deckId: number
  rating: number
  prevStability: number | null
  prevDifficulty: number | null
  prevRetrievability: number | null
  newStability: number | null
  newDifficulty: number | null
  newInterval: number | null
  xpAwarded: number
  wasDelayedReview: boolean
  reviewedAt: Date
  responseTimeMs: number | null
  date: string
}

export interface FeynmanSession {
  id: number
  pathId: number | null
  moduleId: number | null
  concept: string
  targetAudience: string
  explanation: string
  explanationDurationMs: number | null
  aiScore: number | null
  aiScoreAccuracy: number | null
  aiScoreClarity: number | null
  aiScoreDepth: number | null
  aiScoreAnalogy: number | null
  aiFeedback: string | null
  aiGaps: string | null
  aiNextSteps: string | null
  xpEarned: number
  createdAt: Date
}

export interface KnowledgeNode {
  id: number
  pathId: number | null
  concept: string
  description: string | null
  mastery: number
  connections: string
  x: number
  y: number
  color: string
  createdAt: Date
}

export interface LearningAnalytics {
  id: number
  date: string
  pathId: number | null
  focusMinutes: number
  cardsReviewed: number
  feynmanSessionsCount: number
  avgFeynmanScore: number
}


export interface FocusSession {
  id: number
  taskId: number | null
  projectId: number | null
  learningTrackId: number | null
  lessonId: number | null
  type: 'focus' | 'short_break' | 'long_break' | 'free_flow'
  
  plannedMinutes: number
  actualMinutes: number | null
  microRewardsEarned: number // maps to microStarsEarned
  xpEarned: number

  flowState: boolean
  interrupted: boolean
  interruptionReason: string | null
  interruptionCount: number
  interruptionReasons: string // JSON string

  moodBefore: number | null
  moodAfter: number | null
  energyBefore: number | null
  energyAfter: number | null

  pinchActive: string | null
  notes: string | null
  contextSaved: string | null
  
  startedAt: Date
  endedAt: Date | null
  date: string // YYYY-MM-DD
}

export interface Habit {
  id: number
  name: string
  emoji: string
  description: string | null
  type: 'build' | 'break'
  frequency: string
  targetDays: string // JSON representation
  reminderTime: string | null
  energyRequired: 'low' | 'medium' | 'high'
  durationMinutes: number
  dopamineBoost: number
  xpPerCompletion: number
  linkedDopamineId: number | null

  currentStreak: number
  longestStreak: number
  totalCompletions: number
  isActive: boolean
  createdAt: Date
}

export interface HabitLog {
  id: number
  habitId: number
  date: string // YYYY-MM-DD
  completed: boolean
  quality: number
  notes: string | null
  durationMinutes: number | null
  completedAt: Date | null
}

export interface BrainDump {
  id: number
  content: string
  category: string
  aiCategorized: boolean
  aiSuggestion: string | null
  convertedToTaskId: number | null
  convertedToTrackId: number | null
  isArchived: boolean
  urgencyLevel: 'low' | 'medium' | 'high'
  createdAt: Date
}

export interface DopamineActivity {
  id: number
  name: string
  emoji: string
  description: string | null
  category: 'movement' | 'creative' | 'social' | 'sensory' | 'achievement' | 'nature' | 'play'
  durationMinutes: number
  energyCost: 'low' | 'medium' | 'high'
  dopamineScore: number
  useCount: number
  lastUsedAt: Date | null
  isCustom: boolean
  isActive: boolean
  createdAt: Date
}

export interface DopamineLog {
  id: number
  activityId: number
  usedAt: Date
  moodBefore: number | null
  moodAfter: number | null
  notes: string | null
  date: string
}

export interface MoodLog {
  id: number
  date: string
  time: string
  mood: number
  energy: number
  focus: number
  anxiety: number
  emoji: string | null
  notes: string | null
  tags: string // JSON representation
  rsdTriggered: boolean
  triggeredBy: string | null
  createdAt: Date
}

export interface EnergyLog {
  id: number
  date: string
  hour: number
  energyLevel: number
}

export interface XPLedgerEntry {
  id: number
  amount: number
  reason: string
  referenceId: number | null
  referenceType: string | null
  totalAfter: number
  date: string
  createdAt: Date
}

export interface Achievement {
  id: number
  key: string
  name: string
  nameAr: string
  descriptionAr: string
  emoji: string
  category: 'focus' | 'tasks' | 'habits' | 'learning' | 'consistency' | 'courage' | 'special'
  xpReward: number
  rarity: 'common' | 'rare' | 'epic' | 'legendary'
  condition: string // JSON representation
  unlockedAt: Date | null
  isUnlocked: boolean
  isHidden: boolean
}

export interface UserProfile {
  id: number
  name: string
  avatar: string | null
  level: number
  totalXP: number
  currentStreakDays: number
  longestStreakDays: number
  pinchProfile: string // JSON representation
  peakHour: number
  avgDailyEnergy: number
  onboardingCompleted: boolean
  createdAt: Date
}

export interface ContextSnapshot {
  id: number
  taskId: number | null
  projectId: number | null
  learningTrackId: number | null
  snapshot: string // JSON representation
  createdAt: Date
}

export interface AppSettings {
  [key: string]: string
}

export interface LearningMaterial {
  id: number
  title: string
  content: string | null
  filePath: string | null
  fileSize: number | null
  fileType: string | null // 'pdf', 'txt', 'markdown', 'link', 'text_input'
  learningTrackId: number | null
  status: 'pending' | 'reading' | 'summarized' | 'read'
  summary: string | null // markdown summary
  conceptMap: string | null // JSON string of 3D nodes/links
  createdAt: Date
  updatedAt: Date | null
}

export interface Note {
  id: number
  title: string
  content: string
  tags: string // JSON representation string[]
  emoji: string
  color: string | null
  linkedTaskId: number | null
  linkedProjectId: number | null
  linkedPathId: number | null
  linkedModuleId: number | null
  area: string // 'projects' | 'areas' | 'resources' | 'archive' | 'uncategorized'
  aiSummary: string | null
  aiKeywords: string // JSON representation string[]
  embeddingHash: string | null
  searchContent: string | null
  wordCount: number
  isArchived: boolean
  isPinned: boolean
  createdAt: Date | string
  updatedAt: Date | string | null
}

export interface NoteLink {
  id: number
  sourceNoteId: number
  targetNoteId: number
  linkType: string
  context: string | null
  createdAt: Date | string
}

export interface JournalEntry {
  id: number
  date: string // YYYY-MM-DD
  type: 'morning' | 'evening' | 'shame_breaker' | 'decision' | 'free'
  content: string
  prompt: string | null
  primaryEmotion: string | null
  secondaryEmotion: string | null
  emotionIntensity: number | null
  emotionColor: string | null
  energyAtWrite: number | null
  moodAtWrite: number | null
  sleepLastNight: number | null
  aiInsights: string | null
  aiDetectedPatterns: string | null // JSON string
  aiShameLevel: number | null
  aiActionSuggested: string | null
  relatedNoteId: number | null
  xpEarned: number
  wordCount: number
  durationMinutes: number | null
  createdAt: Date | string
}

export interface BodyDoubleSession {
  id: number
  focusSessionId: number | null
  personaName: string
  ambientType: 'silent' | 'subtle' | 'active'
  soundscape: string | null
  checkInIntervalMin: number
  voiceEnabled: boolean
  plannedMinutes: number
  actualMinutes: number | null
  checkInsCount: number
  driftDetectedCount: number
  affirmationsGiven: string // JSON list
  taskCompleted: boolean
  userRating: number | null
  startedAt: Date | string
  endedAt: Date | string | null
  date: string // YYYY-MM-DD
}

export interface SleepLog {
  id: number
  date: string // YYYY-MM-DD
  bedTime: string | null // HH:MM
  wakeTime: string | null // HH:MM
  totalHours: number | null
  quality: number | null
  fellAsleepMin: number | null
  racingThoughts: boolean
  midnightWakeups: number
  medicationTaken: boolean
  notes: string | null
  aiInsight: string | null
  createdAt: Date | string
}

export interface PatternInsight {
  id?: number
  type: string
  title: string
  description: string
  confidence: number
  dataPointCount: number | null
  recommendation: string | null
  correlationValue: number | null
  chartData: string | null
  isNew: boolean
  isActedOn: boolean
  validFrom: string | null
  generatedAt: Date | string
}

export interface Commitment {
  id: number
  title: string
  description: string | null
  type: string // 'learning' | 'habit' | 'project' | 'daily_routine' | 'custom'
  commitment: string
  whyItMatters: string | null
  obstaclesPlan: string | null
  rewardPlan: string | null
  linkedPathId: number | null
  linkedHabitId: number | null
  linkedProjectId: number | null
  startDate: string // YYYY-MM-DD
  endDate: string | null // YYYY-MM-DD
  durationDays: number | null
  status: string // 'active' | 'completed' | 'broken' | 'renewed'
  streak: number
  completionRate: number // 0-100
  aiCheckinEnabled: boolean
  lastCheckin: Date | string | null
  createdAt: Date | string
  completedAt: Date | string | null
}


