import { sqliteTable, text, integer } from 'drizzle-orm/sqlite-core';
import { learningPaths } from './learningPaths.schema';

export const learningModules = sqliteTable('learning_modules', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  pathId: integer('path_id').notNull().references(() => learningPaths.id, { onDelete: 'cascade' }),
  order: integer('order').notNull(),
  title: text('title').notNull(),
  type: text('type').notNull().default('lesson'), // 'lesson' | 'quiz' | 'feynman' | 'project' | 'review'

  // Microlearning
  content: text('content'),          // JSON: microchunks array
  estimatedMinutes: integer('est_min').default(20),
  microchunkCount: integer('chunks').default(1),

  // Status
  status: text('status').default('pending'), // 'pending' | 'in_progress' | 'done' | 'skipped'

  // AI-generated flashcards from this module
  autoGeneratedCards: integer('auto_cards', { mode: 'boolean' }).default(false),
  cardCount: integer('card_count').default(0),

  notes: text('notes'),
  keyPoints: text('key_points'),     // JSON array of key points
  completedAt: integer('completed_at', { mode: 'timestamp' }),
});
